AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for hosting Mapshot-generated files in Sydney with custom domain and CloudFront using latest TLS and OAC'

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The ID of the hosted zone where the domain is managed

  DomainName:
    Type: String
    Description: The domain name for the static website (e.g., example.com)

  CertificateArn:
    Type: String
    Description: The ARN of the externally provided SSL/TLS certificate

Resources:
  MapShotBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${DomainName}-${AWS::StackName}'
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  MapShotBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MapShotBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MapShotBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${MapShotCloudFrontDistribution}'

  MapShotOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: MapShotOAC
        SigningBehavior: always
        OriginAccessControlOriginType: s3
        SigningProtocol: sigv4

  MapShotCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: !Sub 'CloudFront distribution for bucket ${MapShotBucket}'
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: S3Origin
          MinTTL: 0
          DefaultTTL: 300
          MaxTTL: 1200
          ForwardedValues:
            QueryString: false
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt MapShotBucket.DomainName
            Id: S3Origin
            S3OriginConfig: {}
            OriginAccessControlId: !Ref MapShotOriginAccessControl
        PriceClass: PriceClass_100
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  WebsiteDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt MapShotCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt MapShotCloudFrontDistribution.DomainName
    Description: Domain name of CloudFront distribution
  DomainName:
    Value: !Ref DomainName
    Description: Domain name for the static website

# index.html not set on cloudfront distribution!